version: "3"
services:
    db:  
       image: mysql:latest
       container_name: mysql_container
       volumes:
            - mysql_volume:/var/lib/mysql
       networks:
            - my_network     
       environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=Davita
         
    diagnosis-app-backend:
       image: diagnosis:1.0
       container_name: diagnosis_app
       networks:
            - my_network
       environment:
            - RDS_HOSTNAME=mysql_container
       depends_on:
            - db
       ports:
            - "8080:8080"
        
            
volumes:
    mysql_volume:

networks:
    my_network:
